name: Python application

on:
  push:
    branches: [ main ]

env:
    DOCKER_HUB_USERNAME: ${secrets.DOCKER_HUB_USERNAME}
    DOCKER_HUB_ACCESS_TOKEN: ${secrets.DOCKER_HUB_ACCESS_TOKEN}
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: |
          * 
          !.git


  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: app
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
         username: bhushanmisal531
         password: dckr_pat_g2Iejlm8cF_XB7KPVFJJ-36ts3I
         
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.0.1
      with:
       context: .
       push: true
       tags: 
         bhushanmisal531/tririga-omp:0.0.1.RELESE
          
          
          
